[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.22"

[features]
resolution = false
skip-lint = false

[programs.devnet]
faucet = "7TfpKdoDVa58JpZpMX3Tq8gYT9RcSr7XKqimYnGLrGQP"
perpetuals = "Af8eHTdgfsgCk4Z5GViFEBPCkL5fKpE4N6V8G8qwgGnd"

[programs.localnet]
faucet = "7TfpKdoDVa58JpZpMX3Tq8gYT9RcSr7XKqimYnGLrGQP"
perpetuals = "Af8eHTdgfsgCk4Z5GViFEBPCkL5fKpE4N6V8G8qwgGnd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/perpetuals", "programs/faucet"]

[scripts]
startup_wait = "100000"
test = "npm run test"
