[features]
seeds = false
skip-lint = false
[programs.devnet]
perpetuals = "6iQGU4VcVkZXzVbFq6jpceXw1V6YfGnM38ujrKZ32cz8"
simulator = "BfHV8RBTKSKFCkCYdbwyPEb3DLACKfBzq8Y2FPXipiaC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/user/.config/solana/id.json"

[workspace]
members = ["programs/perpetuals", "programs/simulator"]

[scripts]
startup_wait = "100000"
test = "npm run test"
