[features]
seeds = false
skip-lint = false
[programs.devnet]
faucet = "AVyirMo5eEE9KMmpfD8B5otX1MBcPbQdfrBAnxBjTMJQ"
perpetuals = "A1yYp7xVyNqqHSfSw2hMK8XvQHwGytiBjrabLAucBsqJ"

[programs.localnet]
faucet = "AVyirMo5eEE9KMmpfD8B5otX1MBcPbQdfrBAnxBjTMJQ"
perpetuals = "A1yYp7xVyNqqHSfSw2hMK8XvQHwGytiBjrabLAucBsqJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/perpetuals", "programs/faucet"]

[scripts]
startup_wait = "100000"
test = "npm run test"
