[features]
seeds = false
skip-lint = false
[programs.devnet]
perpetuals = "GkZTLm2G9BFeZU6MRarJHt4CgTkRL9m2tZWvyhvBzMaF"
simulator = "BfHV8RBTKSKFCkCYdbwyPEb3DLACKfBzq8Y2FPXipiaC"

[programs.localnet]
perpetuals = "GkZTLm2G9BFeZU6MRarJHt4CgTkRL9m2tZWvyhvBzMaF"
simulator = "BfHV8RBTKSKFCkCYdbwyPEb3DLACKfBzq8Y2FPXipiaC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/user/.config/solana/id.json"

[workspace]
members = [
  "programs/perpetuals",
  "programs/simulator"
]

[scripts]
startup_wait = "100000"
test = "npm run test"
