[features]
seeds = false
skip-lint = false
[programs.devnet]
faucet = "JArCk1B16SwusW63tvTfUzVmKFgRtCMQENB4rrHzu8FV"
perpetuals = "4NUsfUUaQRyhtQ4Q3qu33sfvmFhBhGu2V3xUCs5393kB"

[programs.localnet]
faucet = "JArCk1B16SwusW63tvTfUzVmKFgRtCMQENB4rrHzu8FV"
perpetuals = "4NUsfUUaQRyhtQ4Q3qu33sfvmFhBhGu2V3xUCs5393kB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/user/.config/solana/id.json"

[workspace]
members = ["programs/perpetuals", "programs/faucet"]

[scripts]
startup_wait = "100000"
test = "npm run test"
