[features]
seeds = false
skip-lint = false
[programs.devnet]
perpetuals = "3imnxzymKGjYChfh7VsCMPB9TWpXuaM9QCnDBnQiF7AC"

[programs.localnet]
perpetuals = "3imnxzymKGjYChfh7VsCMPB9TWpXuaM9QCnDBnQiF7AC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
startup_wait = "100000"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 programs/perpetuals/tests/anchor/*.ts"
