[features]
seeds = false
skip-lint = false
[programs.devnet]
faucet = "BPXsk7o3PWaXMNJRyUk7m7VogYZQYAVXeNgPd5j1Dq9S"
perpetuals = "3y8uRqmgteNMQYUGiMZPCkr585Lmen8mLq1hp2N7auJr"

[programs.localnet]
faucet = "BPXsk7o3PWaXMNJRyUk7m7VogYZQYAVXeNgPd5j1Dq9S"
perpetuals = "3y8uRqmgteNMQYUGiMZPCkr585Lmen8mLq1hp2N7auJr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/user/.config/solana/id.json"

[workspace]
members = ["programs/perpetuals", "programs/faucet"]

[scripts]
startup_wait = "100000"
test = "npm run test"
