[features]
seeds = false
skip-lint = false
[programs.devnet]
perpetuals = "3F6AGgSQpQ4fdqLv2k2erfit2taeCJd1RaSREsuSAq1z"

[programs.localnet]
perpetuals = "5Ws7mKtjDAoujNajobNat1Z16EUUnAq68ps2Y93PYq9u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
startup_wait = "100000"
test = "npm run test"
