[features]
seeds = false
skip-lint = false
[programs.devnet]
perpetuals = "GkZTLm2G9BFeZU6MRarJHt4CgTkRL9m2tZWvyhvBzMaF"

[programs.localnet]
perpetuals = "GkZTLm2G9BFeZU6MRarJHt4CgTkRL9m2tZWvyhvBzMaF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/user/.config/solana/id.json"

[scripts]
startup_wait = "100000"
test = "npm run test"
