[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.22"

[features]
resolution = false
skip-lint = false

[programs.devnet]
faucet = "3TkyhpJ9zhUmZ8Ao3269g7Rwz2N4ZumgnGAp3TwZjdhT"
perpetuals = "BYebp9bdeK45oNLKxpacWJYq9Fy3TSzNN3Yn3iRaxtam"

[programs.localnet]
faucet = "3TkyhpJ9zhUmZ8Ao3269g7Rwz2N4ZumgnGAp3TwZjdhT"
perpetuals = "BYebp9bdeK45oNLKxpacWJYq9Fy3TSzNN3Yn3iRaxtam"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/perpetuals", "programs/faucet"]

[scripts]
startup_wait = "100000"
test = "npm run test"
